FROM python:3.10

WORKDIR /app

COPY frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend /app

CMD ["streamlit", "run", "front_end/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
